export const GET_SESSION_INITIAL = 'user.GET_SESSION_INITIAL'
export const GET_SESSION_SUCCESS = 'user.GET_SESSION_SUCCESS'
export const GET_SESSION_FAILURE = 'user.GET_SESSION_FAILURE'

export const LOGIN_INITIAL = 'user.LOGIN_INITIAL'
export const LOGIN_SUCCESS = 'user.LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'user.LOGIN_FAILURE'

export const LOGOUT_INITIAL = 'user.LOGOUT_INITIAL'
export const LOGOUT_SUCCESS = 'user.LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'user.LOGOUT_FAILURE'

export const REGISTER_INITIAL = 'user.REGISTER_INITIAL'
export const REGISTER_SUCCESS = 'user.REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'user.REGISTER_FAILURE'
